source 'http://rubygems.org'

gem 'rails', '3.0.11'
gem 'devise'
gem 'will_paginate'
gem 'russian'
#gem 'uploadify'
#gem 'rmagick'
gem 'paperclip'
gem 'machinist'
#gem 'faker'
gem 'mysql2', '~> 0.2.7'
gem "rack",  "1.2.5"
gem 'jquery-rails'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git', :branch => 'rails-3.0'

gem 'capistrano'
gem 'unicorn'

gem 'i18n'
gem 'mail'
gem 'tzinfo'
gem 'fastthread'
gem 'rake'
gem 'mime-types'
gem 'enumerated_attribute'
